# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcSerialNo', models.CharField(max_length=50, verbose_name='\u6d88\u606f\u7f16\u53f7')),
                ('vcChatRoomSerialNo', models.CharField(max_length=50, verbose_name='\u7fa4\u7f16\u53f7')),
                ('vcFromWxUserSerialNo', models.CharField(max_length=50, verbose_name='\u53d1\u8a00\u4eba\u7528\u6237\u7f16\u53f7')),
                ('dtMsgTime', models.DateTimeField(blank=True, null=True, verbose_name='\u6d88\u606f\u65f6\u95f4')),
                ('nMsgType', models.IntegerField(blank=True, null=True, verbose_name='\u6d88\u606f\u7c7b\u578b')),
                ('vcContent', models.TextField(blank=True, null=True, verbose_name='\u6587\u672c\u6d88\u606f\u5185\u5bb9')),
                ('nVoiceTime', models.CharField(blank=True, max_length=5, null=True, verbose_name='\u8bed\u97f3\u65f6\u957f')),
                ('vcShareTitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u94fe\u63a5\u6807\u9898')),
                ('vcShareDesc', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u94fe\u63a5\u63cf\u8ff0')),
                ('vcShareUrl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u94fe\u63a5url')),
            ],
            options={
                'ordering': ['-dtMsgTime'],
                'db_table': 'chatmessage',
                'verbose_name': '\u7fa4\u5185\u804a\u5929\u4fe1\u606f',
                'verbose_name_plural': '\u7fa4\u5185\u804a\u5929\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ChatRoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcChatRoomSerialNo', models.CharField(max_length=50, unique=True, verbose_name='\u7fa4\u7f16\u53f7')),
                ('vcName', models.CharField(max_length=50, verbose_name='\u7fa4\u6635\u79f0')),
                ('vcBase64Name', models.CharField(max_length=100, verbose_name='base64\u7f16\u7801\u540e\u7684\u7fa4\u6635\u79f0')),
                ('vcWxUserSerialNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5f00\u7fa4\u7528\u6237\u7f16\u53f7')),
                ('vcWxManagerUserSerialNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7fa4\u4e3b\u7684\u5fae\u4fe1\u7528\u6237\u7f16\u53f7')),
                ('vcRobotSerialNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u673a\u5668\u4eba\u7f16\u53f7')),
                ('vcApplyCodeSerialNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u9a8c\u8bc1\u7801\u7f16\u53f7')),
            ],
            options={
                'db_table': 'chatroom_info',
                'verbose_name': '\u7fa4\u4fe1\u606f',
                'verbose_name_plural': '\u7fa4\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='DropOutChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcChatRoomSerialNo', models.CharField(max_length=50, verbose_name='\u7fa4\u7f16\u53f7')),
                ('vcWxUserSerialNo', models.CharField(max_length=50, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('dtCreateDate', models.DateTimeField(verbose_name='\u9000\u7fa4\u65f6\u95f4')),
            ],
            options={
                'db_table': 'drop_out_chatroom',
                'verbose_name': '\u6210\u5458\u9000\u7fa4\u6d88\u606f',
                'verbose_name_plural': '\u6210\u5458\u9000\u7fa4\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='IntoChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcChatRoomSerialNo', models.CharField(max_length=50, verbose_name='\u7fa4\u7f16\u53f7')),
                ('vcWxUserSerialNo', models.CharField(max_length=50, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('vcFatherWxUserSerialNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7528\u6237\u7236\u7ea7\u7f16\u53f7\uff08\u9080\u8bf7\u4eba\u7f16\u53f7\uff09')),
                ('vcNickName', models.CharField(max_length=20, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('vcBase64NickName', models.CharField(max_length=100, verbose_name='Base64\u7f16\u7801\u540e\u7684\u7528\u6237\u6635\u79f0')),
                ('vcHeadImages', models.CharField(max_length=1000, verbose_name='\u7528\u6237\u5934\u50cf')),
                ('nJoinChatRoomType', models.CharField(max_length=5, verbose_name='\u5165\u7fa4\u65b9\u5f0f')),
                ('message_create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6d88\u606f\u83b7\u53d6\u65f6\u95f4')),
            ],
            options={
                'db_table': 'into_chatroom',
                'verbose_name': '\u6210\u5458\u5165\u7fa4\u6d88\u606f',
                'verbose_name_plural': '\u6210\u5458\u5165\u7fa4\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='IntoChatRoomMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcSerialNo', models.CharField(max_length=50, verbose_name='\u62c9\u7fa4\u7f16\u53f7')),
                ('vcRobotSerialNo', models.CharField(max_length=50, verbose_name='\u673a\u5668\u4eba\u7f16\u53f7')),
                ('vcName', models.CharField(max_length=50, verbose_name='\u7fa4\u6635\u79f0')),
                ('vcBase64Name', models.CharField(max_length=100, verbose_name='\u7fa4base64\u7f16\u7801\u540e\u7684\u6635\u79f0')),
                ('vcWxUserSerialNo', models.CharField(max_length=50, verbose_name='\u62c9\u7fa4\u7528\u6237\u7684\u5fae\u4fe1\u7f16\u53f7')),
                ('vcNickName', models.CharField(max_length=20, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('vcBase64NickName', models.CharField(max_length=100, verbose_name='\u7528\u6237base64\u7f16\u7801\u540e\u7684\u6635\u79f0')),
                ('vcHeadImgUrl', models.CharField(max_length=1000, verbose_name='\u7528\u6237\u5934\u50cf')),
                ('dtCreateDate', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'into_chatroom_message',
                'verbose_name': '\u5165\u7fa4\u56de\u8c03\u6d88\u606f',
                'verbose_name_plural': '\u5165\u7fa4\u56de\u8c03\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcSerialNo', models.CharField(max_length=50, unique=True, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('vcNickName', models.CharField(max_length=100, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('vcBase64NickName', models.CharField(max_length=100, verbose_name='Base64\u7f16\u7801\u540e\u7684\u7528\u6237\u6635\u79f0')),
                ('vcHeadImages', models.CharField(max_length=1000, verbose_name='\u7528\u6237\u5934\u50cf')),
                ('nJoinChatRoomType', models.CharField(max_length=5, verbose_name='\u5165\u7fa4\u65b9\u5f0f')),
                ('vcFatherWxUserSerialNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7528\u6237\u7236\u7ea7\u7f16\u53f7(\u9080\u8bf7\u4eba\u7f16\u53f7)')),
                ('nMsgCount', models.CharField(max_length=10, verbose_name='\u5f53\u5929\u53d1\u8a00\u603b\u6570')),
                ('dtLastMsgDate', models.DateTimeField(blank=True, null=True, verbose_name='\u5f53\u5929\u6700\u540e\u53d1\u8a00\u65f6\u95f4')),
                ('dtCreateDate', models.DateTimeField(blank=True, null=True, verbose_name='\u5165\u7fa4\u65f6\u95f4')),
            ],
            options={
                'db_table': 'member_info',
                'verbose_name': '\u7fa4\u6210\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u7fa4\u6210\u5458\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='URobotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcSerialNo', models.CharField(max_length=50, unique=True, verbose_name='\u52a9\u624b\u7f16\u53f7')),
                ('nChatRoomCount', models.CharField(max_length=5, verbose_name='\u5165\u7fa4\u6570')),
                ('vcNickName', models.CharField(max_length=20, verbose_name='\u52a9\u624b\u6635\u79f0')),
                ('vcBase64NickName', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u52a9\u624bbase64\u6635\u79f0')),
                ('vcHeadImages', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u52a9\u624b\u5934\u50cf')),
                ('vcCodeImages', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u52a9\u624b\u4e8c\u7ef4\u7801')),
                ('nStatus', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u52a9\u624b\u72b6\u6001')),
                ('status', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
            ],
            options={
                'db_table': 'robot_info',
                'verbose_name': '\u52a9\u624b\u4fe1\u606f',
                'verbose_name_plural': '\u52a9\u624b\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='chatroommodel',
            name='member',
            field=models.ManyToManyField(blank=True, to='connector.MemberInfo', verbose_name='\u7fa4\u6210\u5458'),
        ),
    ]
