# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommodel',
            name='serNum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5e93\u7f16\u53f7'),
        ),
    ]
