# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_chatroommodel_sernum'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, verbose_name='\u5efa\u7fa4\u4efb\u52a1\u7f16\u53f7')),
                ('serNum', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5e93\u7f16\u53f7')),
            ],
            options={
                'db_table': 'roomtask',
                'verbose_name': '\u5efa\u7fa4\u4efb\u52a1\u4fe1\u606f',
                'verbose_name_plural': '\u5efa\u7fa4\u4efb\u52a1\u4fe1\u606f',
            },
        ),
    ]
