# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_roomtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommodel',
            name='vcBase64Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='base64\u7f16\u7801\u540e\u7684\u7fa4\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='intochatroom',
            name='vcNickName',
            field=models.CharField(max_length=100, verbose_name='\u7528\u6237\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='intochatroommessagemodel',
            name='vcNickName',
            field=models.CharField(max_length=100, verbose_name='\u7528\u6237\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='urobotmodel',
            name='vcNickName',
            field=models.CharField(max_length=100, verbose_name='\u52a9\u624b\u6635\u79f0'),
        ),
    ]
