# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_auto_20170714_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='intochatroommessagemodel',
            name='state',
            field=models.CharField(default=1, max_length=10, verbose_name='\u662f\u5426\u5df2\u7ecf\u5f00\u7fa4'),
        ),
    ]
