# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_intochatroommessagemodel_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcRobotSerialNo', models.CharField(max_length=50, verbose_name='\u673a\u5668\u4eba\u7f16\u53f7')),
                ('vcChatRoomSerialNo', models.CharField(max_length=50, verbose_name='\u7fa4\u7f16\u53f7')),
                ('state', models.CharField(default=0, max_length=10, verbose_name='\u662f\u5426\u5728\u7fa4\u5185')),
            ],
            options={
                'db_table': 'robotchatroom',
                'verbose_name': '\u673a\u5668\u4eba\u7fa4\u4fe1\u606f',
                'verbose_name_plural': '\u673a\u5668\u4eba\u7fa4\u4fe1\u606f',
            },
        ),
    ]
