# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0006_robotchatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemiiRobot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcRobotSerialNo', models.CharField(max_length=50, verbose_name='\u673a\u5668\u4eba\u7f16\u53f7')),
                ('vcName', models.CharField(max_length=100, verbose_name='\u673a\u5668\u4eba\u540d\u79f0')),
                ('qrcode', models.CharField(max_length=255, verbose_name='\u673a\u5668\u4eba\u4e8c\u7ef4\u7801')),
            ],
            options={
                'db_table': 'gemiirobot',
                'verbose_name': '\u666f\u6817\u8bbe\u5907',
                'verbose_name_plural': '\u666f\u6817\u8bbe\u5907',
            },
        ),
    ]
