# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_gemiirobot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemiirobot',
            name='vcRobotSerialNo',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u673a\u5668\u4eba\u7f16\u53f7'),
        ),
    ]
