# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_auto_20170721_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcChatRoomSerialNo', models.CharField(max_length=50, verbose_name='\u7fa4\u7f16\u53f7')),
                ('vcWxUserSerialNo', models.CharField(max_length=50, verbose_name='\u7528\u6237\u7f16\u53f7')),
            ],
            options={
                'db_table': 'WhileList',
                'verbose_name': '\u767d\u540d\u5355\u5217\u8868',
                'verbose_name_plural': '\u767d\u540d\u5355\u5217\u8868',
            },
        ),
    ]
