# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0010_whilelist_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotBlockedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcSerialNo', models.CharField(max_length=50, verbose_name='\u673a\u5668\u4eba\u7f16\u53f7')),
                ('nChatRoomCount', models.CharField(max_length=5, verbose_name='\u5f00\u901a\u7684\u7fa4\u6570\u91cf')),
                ('vcNickName', models.CharField(max_length=50, verbose_name='\u673a\u5668\u4eba\u6635\u79f0')),
                ('vcBase64NickName', models.CharField(max_length=100, verbose_name='\u673a\u5668\u4ebabase64\u7f16\u7801\u540e\u7684\u6635\u79f0')),
                ('vcHeadImages', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u52a9\u624b\u5934\u50cf')),
                ('vcCodeImages', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u52a9\u624b\u4e8c\u7ef4\u7801')),
                ('nStatus', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u52a9\u624b\u72b6\u6001')),
                ('dtCreateDate', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'robotblocked',
                'verbose_name': '\u673a\u5668\u4eba\u88ab\u5c01\u4fe1\u606f',
                'verbose_name_plural': '\u673a\u5668\u4eba\u88ab\u5c01\u4fe1\u606f',
            },
        ),
    ]
