# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0011_robotblockedmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='robotchatroom',
            unique_together=set([('vcRobotSerialNo', 'vcChatRoomSerialNo')]),
        ),
    ]
