# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0012_auto_20170801_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='nMsgCount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5f53\u5929\u53d1\u8a00\u603b\u6570'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='vcBase64NickName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Base64\u7f16\u7801\u540e\u7684\u7528\u6237\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='vcHeadImages',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='vcNickName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7528\u6237\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='robotblockedmodel',
            name='nChatRoomCount',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='\u5f00\u901a\u7684\u7fa4\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='robotblockedmodel',
            name='vcBase64NickName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u673a\u5668\u4ebabase64\u7f16\u7801\u540e\u7684\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='robotblockedmodel',
            name='vcNickName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u673a\u5668\u4eba\u6635\u79f0'),
        ),
    ]
