# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0013_auto_20170803_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtask',
            name='bot_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u9879\u76ee\u533a\u5206\u7f16\u53f7'),
        ),
    ]
