# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0014_roomtask_bot_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMsgFailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcRelaSerialNo', models.CharField(max_length=50, verbose_name='\u5546\u5bb6\u7f16\u53f7')),
                ('nMsgNum', models.CharField(max_length=50, verbose_name='\u6d88\u606f\u7f16\u53f7')),
            ],
            options={
                'db_table': 'failmessage',
                'verbose_name': '\u53d1\u9001\u5931\u8d25\u7684\u6d88\u606f',
                'verbose_name_plural': '\u53d1\u9001\u5931\u8d25\u7684\u6d88\u606f',
            },
        ),
    ]
