# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0015_sendmsgfailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmsgfailmodel',
            name='message_receive_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6d88\u606f\u63a5\u6536\u65f6\u95f4'),
        ),
    ]
