# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0016_sendmsgfailmodel_message_receive_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailMemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NickName', models.CharField(max_length=50, verbose_name='\u5546\u5bb6\u7f16\u53f7')),
                ('Email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1\u5730\u5740')),
                ('send_type', models.CharField(help_text='rb\u8868\u793a\u88ab\u5c01\u673a\u5668\u4eba\u53d1\u90ae\u4ef6', max_length=10, verbose_name='\u53d1\u9001\u90ae\u4ef6\u7c7b\u578b')),
            ],
        ),
    ]
