# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0017_sendemailmembermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemailmembermodel',
            options={'verbose_name': '\u53d1\u9001\u90ae\u4ef6\u6210\u5458\u8868', 'verbose_name_plural': '\u53d1\u9001\u90ae\u4ef6\u6210\u5458\u8868'},
        ),
        migrations.AlterModelTable(
            name='sendemailmembermodel',
            table='send_email_member',
        ),
    ]
