# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0018_auto_20170828_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemailmembermodel',
            name='NickName',
            field=models.CharField(max_length=50, verbose_name='\u7528\u6237\u540d\u79f0'),
        ),
    ]
