# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0020_auto_20170906_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intochatroom',
            name='nJoinChatRoomType',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='\u5165\u7fa4\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='intochatroom',
            name='vcBase64NickName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Base64\u7f16\u7801\u540e\u7684\u7528\u6237\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='intochatroom',
            name='vcHeadImages',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='intochatroom',
            name='vcNickName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7528\u6237\u6635\u79f0'),
        ),
    ]
