# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomIdMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, verbose_name='\u666f\u6817\u7fa4id')),
                ('u_room_id', models.CharField(max_length=50, verbose_name='\u7531\u521b\u7fa4id')),
                ('name', models.CharField(max_length=20, verbose_name='\u7fa4\u540d')),
            ],
            options={
                'db_table': 'room_id_map',
                'verbose_name': '\u7fa4id\u6620\u5c04\u8868',
                'verbose_name_plural': '\u7fa4id\u6620\u5c04\u8868',
            },
        ),
    ]
